# Site settings
title: IHomer Blog
email: xander@ihomer.nl
description: > # this means to ignore newlines until "baseurl:"
  IHomer Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ihomer.nl" # the base hostname & protocol for your site
twitter_username: ihomer
github_username:  ihomer

# Build settings
markdown: kramdown
